#!/bin/bash

cd $ULTIMATE_DIR
ULTIMATE_MAIN_DIR=$(dirname "$(pwd)")
NUM_TESTS_FAILED=0
while IFS="," read -ra line; do
    line[0]="${line[0]//\\ / }"
    printf "\nTesting ${line[0]} - ${line[1]} - ${line[2]}"
    output=$(java -jar $ULTIMATE_DIR/target/ultimate-headless.jar -pf "$ULTIMATE_MAIN_DIR/${line[0]}" -m "${line[1]}" -p "${line[2]}" 2>&1)
    result=\0
    if [[ $output =~ Result:\ ([^[:space:]]+) ]]; then
        result="${BASH_REMATCH[1]}"
    fi

    if [[ $result==${line[3]} ]]; then
        printf ": PASS --- expected result was obtained ($result)."
    else
        printf "\nFAIL --- ULTIMATE output was:\n$output\n"
        NUM_TESTS_FAILED=$NUM_TESTS_FAILED+1
    fi
done < $ULTIMATE_MAIN_DIR/testing/expected_results.csv

if [[ $NUM_TESTS_FAILED != 0 ]]; then
    printf "\nFAILURE: $NUM_TESTS_FAILED tests failed (see above for details)."
else
    printf "\nSUCCESS: No tests failed."
fi


